//! Application screens module.

mod contract;
mod get_contract;
mod get_identity;
mod identity;
mod main;
mod wallet;
mod add_wallet;
mod strategies;
mod strategy_create;
mod strategy_confirm;

pub(crate) use contract::ContractScreen;
pub(crate) use contract::ContractScreenCommands;
pub(crate) use get_contract::GetContractScreen;
pub(crate) use get_contract::GetContractScreenCommands;
pub(crate) use get_contract::ContractIdInput;
pub(crate) use get_identity::GetIdentityScreen;
pub(crate) use get_identity::GetIdentityScreenCommands;
pub(crate) use get_identity::IdentityIdInput;
pub(crate) use identity::IdentityScreen;
pub(crate) use identity::IdentityScreenCommands;
pub(crate) use main::MainScreen;
pub(crate) use main::MainScreenCommands;
pub(crate) use wallet::WalletScreen;
pub(crate) use wallet::WalletScreenCommands;
pub(crate) use add_wallet::AddWalletScreen;
pub(crate) use add_wallet::AddWalletScreenCommands;
pub(crate) use add_wallet::PrivateKeyInput;
pub(crate) use strategies::StrategiesScreen;
pub(crate) use strategies::StrategiesScreenCommands;
pub(crate) use strategies::StrategySelect;
pub(crate) use strategies::DeleteStrategyStruct;
pub(crate) use strategy_create::CreateStrategyScreen;
pub(crate) use strategy_create::CreateStrategyScreenCommands;
pub(crate) use strategy_create::EditContractsStruct;
pub(crate) use strategy_create::RenameStrategyStruct;
pub(crate) use strategy_create::LoadStrategyStruct;
pub(crate) use strategy_create::SelectOperationTypeStruct;
pub(crate) use strategy_create::DocumentStruct;
pub(crate) use strategy_confirm::ConfirmStrategyScreen;
pub(crate) use strategy_confirm::ConfirmStrategyScreenCommands;
